name: Example Workflow
on: [ push ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, this is running on a self-hosted runner!"
        check-ts:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              node-version: [ 20 ]
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci



