name: Example Workflow
on: [ push ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Hello, this is running on a self-hosted runner!"
