name: Example Workflow
permissions: write-all
on: [ push ]
jobs:
  test-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 20 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install dependencies
        run: yarn install

      - name: build:vite-common
        run: yarn build:vite-common

      - name: client-home
        run: cd ./packages/client-home && yarn build
